ALTER TABLE OBJECT ADD SiteNum INT;
ALTER TABLE OBJECT ADD CONSTRAINT FOREIGN KEY(SiteNum) REFERENCES SITES(SiteNum);

ALTER TABLE RESEARCHERS ADD ObjectNum INT NOT NULL;
ALTER TABLE RESEARCHERS ADD CONSTRAINT FOREIGN KEY(ObjectNum) REFERENCES OBJECT(Object_num);
ALTER TABLE RESEARCHERS ADD SiteNum INT;
ALTER TABLE RESEARCHERS ADD CONSTRAINT FOREIGN KEY(SiteNum) REFERENCES SITES(SiteNum);
ALTER TABLE RESEARCHERS ADD SSN INT NOT NULL;
ALTER TABLE RESEARCHERS ADD CONSTRAINT FOREIGN KEY(SSN) REFERENCES EMPLOYEE_INFO(SSN);

ALTER TABLE AGENTS ADD Dnum INT NOT NULL;
ALTER TABLE AGENTS ADD CONSTRAINT FOREIGN KEY(Dnum) REFERENCES DEPARTMENTS(Dnum);
ALTER TABLE AGENTS ADD ObjectNum INT NOT NULL;
ALTER TABLE AGENTS ADD CONSTRAINT FOREIGN KEY(ObjectNum) REFERENCES DEPARTMENTS(Object_num);
ALTER TABLE AGENTS ADD MissionNum INT;
ALTER TABLE AGENTS ADD CONSTRAINT FOREIGN KEY(MissionNum) REFERENCES MISSION(MissionNum);
ALTER TABLE AGENTS ADD SSN INT NOT NULL;
ALTER TABLE AGENTS ADD CONSTRAINT FOREIGN KEY(SSN) REFERENCES EMPLOYEE_INFO(SSN);


ALTER TABLE DIRECTORS ADD Dnum INT NOT NULL;
ALTER TABLE DIRECTORS ADD CONSTRAINT FOREIGN KEY(Dnum) REFERENCES DEPARTMENTS(Dnum);
ALTER TABLE DIRECTORS ADD SSN INT NOT NULL;
ALTER TABLE DIRECTORS ADD CONSTRAINT FOREIGN KEY(SSN) REFERENCES EMPLOYEE_INFO(SSN);

ALTER TABLE SITES ADD Dnum INT NOT NULL;
ALTER TABLE SITES ADD CONSTRAINT FOREIGN KEY(Dnum) REFERENCES DEPARTMENTS(Dnum);

ALTER TABLE RESEARCH_LOG ADD ObjectNum INT NOT NULL;
ALTER TABLE RESEARCH_LOG ADD CONSTRAINT FOREIGN KEY(ObjectNum) REFERENCES OBJECT(Object_num);
ALTER TABLE RESEARCH_LOG ADD Researcher_ID INT NOT NULL;
ALTER TABLE RESEARCH_LOG ADD CONSTRAINT FOREIGN KEY(Researcher_ID) REFERENCES RESEARCHERS(ID);

ALTER TABLE BREACH_LOG ADD ObjectNum INT NOT NULL;
ALTER TABLE BREACH_LOG ADD CONSTRAINT FOREIGN KEY(ObjectNum) REFERENCES OBJECT(Object_num);
ALTER TABLE BREACH_LOG ADD Director_ID INT NOT NULL;
ALTER TABLE BREACH_LOG ADD CONSTRAINT FOREIGN KEY(Director_ID) REFERENCES DIRECTORS(ID);

ALTER TABLE MISSION ADD ObjectNum INT NOT NULL;
ALTER TABLE MISSION ADD CONSTRAINT FOREIGN KEY(ObjectNum) REFERENCES OBJECT(Object_num);
ALTER TABLE MISSION ADD Agent_ID INT NOT NULL;
ALTER TABLE MISSION ADD CONSTRAINT FOREIGN KEY(Agent_ID) REFERENCES AGENTS(ID);

