drop SCHEMA SCPFoundation;
drop TABLE  OBJECT;
drop TABLE  EMPLOYEE_INFO;
drop TABLE  RESEARCHERS;
drop TABLE  AGENTS;
drop TABLE  DIRECTORS;
drop TABLE  DEPARTMENTS;
drop TABLE  SITES;
drop TABLE  RESEARCH_LOG;
drop TABLE  BREACH_LOG;
drop TABLE  MISSION;

CREATE SCHEMA SCPFoundation AUTHORIZATION Noor21;

CREATE TABLE OBJECT(
Object_num INT NOT NULL,
Breach_status VARCHAR(20) NOT NULL, 
Danger_Level INT NOT NULL,
Description VARCHAR(100),
Difficulty INT NOT NULL,
PRIMARY KEY(object_num)
);

CREATE TABLE EMPLOYEE_INFO(
SSN INT NOT NULL,
Fname VARCHAR(20),
Lname VARCHAR(20),
Address VARCHAR(100),
Age INT,
Phone VARCHAR(10),
PRIMARY KEY(SSN)
);

CREATE TABLE RESEARCHERS(
ID INT NOT NULL,
Position VARCHAR(20),
PRIMARY KEY(ID)
);

CREATE TABLE AGENTS(
ID INT NOT NULL,
MTF_Num VARCHAR(20),
PRIMARY KEY(ID)
);

CREATE TABLE DIRECTORS(
ID INT NOT NULL, 
PRIMARY KEY(ID)
);

CREATE TABLE DEPARTMENTS(
Dnum INT NOT NULL, 
Dname VARCHAR(20) NOT NULL,
Description VARCHAR(100),
Location VARCHAR(20),
Phone VARCHAR(10),
PRIMARY KEY(Dnum)
);

CREATE TABLE SITES(
SiteNum INT NOT NULL,
Location VARCHAR(20),
Phone VARCHAR(10),
Status VARCHAR(20),
PRIMARY KEY(SiteNum)
);

CREATE TABLE RESEARCH_LOG(
LogNum INT NOT NULL,
LogDate DATE NOT NULL,
Equipment VARCHAR(20),
Result VARCHAR(20),
PRIMARY KEY(LogNum)
);

CREATE TABLE BREACH_LOG(
BreachNum INT NOT NULL,
BreachDate DATE NOT NULL,
Description VARCHAR(100),
NumAffected INT,
Primary KEY(BreachNum)
);

CREATE TABLE MISSION(
MissionNum INT NOT NULL,
Status VARCHAR(20),
Description VARCHAR(100),
PRIMARY KEY(MissionNum)
);


                                                   