ALTER TABLE OBJECT DROP COLUMN SiteNum;

ALTER TABLE RESEARCHERS DROP COLUMN ObjectNum; 
ALTER TABLE RESEARCHERS DROP COLUMN SiteNum; 
ALTER TABLE RESEARCHERS DROP COLUMN SSN; 

ALTER TABLE AGENTS DROP COLUMN Dnum;
ALTER TABLE AGENTS DROP COLUMN ObjectNum;
ALTER TABLE AGENTS DROP COLUMN MissionNum;
ALTER TABLE AGENTS DROP COLUMN SSN;


ALTER TABLE DIRECTORS DROP COLUMN Dnum;
ALTER TABLE DIRECTORS DROP COLUMN SSN;

ALTER TABLE SITES DROP COLUMN Dnum;

ALTER TABLE RESEARCH_LOG DROP COLUMN ObjectNum;
ALTER TABLE RESEARCH_LOG DROP COLUMN Researcher_ID;

ALTER TABLE BREACH_LOG DROP COLUMN ObjectNum;
ALTER TABLE BREACH_LOG DROP COLUMN Director_ID;

ALTER TABLE MISSION DROP COLUMN ObjectNum;
ALTER TABLE MISSION DROP COLUMN Agent_ID;

drop TABLE 	OBJECT;
drop TABLE  EMPLOYEE_INFO;
drop TABLE  RESEARCHERS;
drop TABLE  AGENTS;
drop TABLE  DIRECTORS;
drop TABLE  DEPARTMENTS;
drop TABLE  SITES;
drop TABLE  RESEARCH_LOG;
drop TABLE  BREACH_LOG;
drop TABLE  MISSION;
